// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ujybKYysx4P9HvuRfJn44cMWPBfD5dY',
    appId: '1:298654330056:web:661062b77a77ef437a49fd',
    messagingSenderId: '298654330056',
    projectId: 'ecommerce-91988',
    authDomain: 'ecommerce-91988.firebaseapp.com',
    storageBucket: 'ecommerce-91988.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3cV-WNwl3IOEWKNrMLAN1-SCaDv0dWq8',
    appId: '1:298654330056:android:ec5138d837f0d4dd7a49fd',
    messagingSenderId: '298654330056',
    projectId: 'ecommerce-91988',
    storageBucket: 'ecommerce-91988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfktQXvL6HJTqw54OnwtyCdezjNwCGEow',
    appId: '1:298654330056:ios:37221893b4149a017a49fd',
    messagingSenderId: '298654330056',
    projectId: 'ecommerce-91988',
    storageBucket: 'ecommerce-91988.appspot.com',
    iosBundleId: 'com.example.ecommerc2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfktQXvL6HJTqw54OnwtyCdezjNwCGEow',
    appId: '1:298654330056:ios:37221893b4149a017a49fd',
    messagingSenderId: '298654330056',
    projectId: 'ecommerce-91988',
    storageBucket: 'ecommerce-91988.appspot.com',
    iosBundleId: 'com.example.ecommerc2',
  );
}
